#!/usr/bin/env python3
"""gen_savestate.py -- emit a registry of every generated static global so the
savestate layer can snapshot them.

Parses generated/doomrpg.h for `extern <type> S_...;` declarations and writes
generated/savestate_registry.c with a table of {&S_x, sizeof(S_x)}. The game's
mutable static state is exactly these S_* globals (instance fields live in heap
objects, captured by the arena snapshot).
"""
import re
import sys
from pathlib import Path

DECL = re.compile(r'^\s*extern\s+(?:const\s+)?(\w+)\s+(S_[A-Za-z0-9_]+)\s*;')

def main():
    header = Path(sys.argv[1]) if len(sys.argv) > 1 else Path("generated/doomrpg.h")
    out = Path(sys.argv[2]) if len(sys.argv) > 2 else Path("generated/savestate_registry.c")

    entries = []
    for line in header.read_text(encoding="utf-8", errors="replace").splitlines():
        m = DECL.match(line)
        if m:
            entries.append((m.group(2), m.group(1)))   # (name, type)
    # de-dup, keep order
    seen, ordered = set(), []
    for n, t in entries:
        if n not in seen:
            seen.add(n); ordered.append((n, t))

    lines = [
        "/* GENERATED by tools/gen_savestate.py -- do not edit. */",
        '#include "doomrpg.h"',
        '#include "savestate.h"',
        "",
        "const SaveSlot g_savestate_statics[] = {",
    ]
    lines += [f"    {{ &{n}, (unsigned)sizeof({n}) }}," for n, _ in ordered]
    lines += [
        "};",
        f"const int g_savestate_statics_count = {len(ordered)};",
        "",
        "/* Named registry for the dev-menu's static-discovery dump. is_int marks",
        "   jint scalars (the candidates for state/stat globals). */",
        "const StaticInfo g_static_info[] = {",
    ]
    lines += [f'    {{ "{n}", &{n}, (unsigned)sizeof({n}), {1 if t == "jint" else 0}, {1 if t == "jref" else 0} }},'
              for n, t in ordered]
    lines += [
        "};",
        f"const int g_static_info_count = {len(ordered)};",
        "",
    ]
    out.write_text("\n".join(lines), encoding="utf-8")
    print(f"gen_savestate: {len(ordered)} static globals -> {out}")

if __name__ == "__main__":
    main()
